#spring:
#  profiles:
#    active: dev
spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    enabled: true
    sender:
      type: web
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  feign:
    enabled: true
    processor:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "3MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8

logging:
  level:
    org.springframework.cloud.sleuth: debug
  path: logs/
  file:
    max-size: 1GB

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'