version: '3'
services:
  redis: 
    image: redis:alpine #指定容器运行的镜像
    container_name: sc-redis #指定自定义容器名称，而不是生成的默认名称
    restart: always #容器总是重新启动
    volumes:
      - ../data/redis:/data #将主机的数据卷或者文件挂载到容器里
    environment:
      - REDIS_PASSWORD=123456 #添加环境变量。您可以使用数组或字典、任何布尔值，布尔值需要用引号引起来，以确保 YML 解析器不会将其转换为 True 或 False。
    networks:
      - sc-net #配置容器连接的网络，引用顶级networks下的条目
    ports:
      - 6379:6379 #本机映射的端口：容器端口
    env_file: .env #从文件添加环境变量，可以是单个值或列表的多个值

  rabbitmq:
    image: rabbitmq:management-alpine  #指定容器运行的镜像
    container_name: sc-rabbitmq #指定自定义容器名称，而不是生成的默认名称
    restart: always #容器总是重新启动
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia #将主机的数据卷或者文件挂载到容器里
    networks:
      - sc-net #配置容器连接的网络，引用顶级networks下的条目
    ports:
      - 5672:5672
      - 15672:15672 #本机映射的端口：容器端口
    env_file: .env #从文件添加环境变量，可以是单个值或列表的多个值

  mysql:
    image: mysql:5.7 #指定容器运行的镜像
    container_name: sc-mysql #指定自定义容器名称，而不是生成的默认名称
    restart: always #容器总是重新启动
    networks:
      - sc-net #配置容器连接的网络，引用顶级networks下的条目
    ports:
      - 3306:3306 #本机映射的端口：容器端口
    volumes:
      - ../data/mysql:/var/lib/mysql #将主机的数据卷或者文件挂载到容器里
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456 #添加环境变量。您可以使用数组或字典、任何布尔值，布尔值需要用引号引起来，以确保 YML 解析器不会将其转换为 True 或 False。

  mysql-init:
    image: mysql:5.7 #指定容器运行的镜像
    command: /init-db.sh #覆盖容器启动的默认命令
    networks:
      - sc-net #配置容器连接的网络，引用顶级networks下的条目
    volumes:
      - ../auth/db:/sql/auth
      - ../gateway/gateway-admin/src/main/db:/sql/gateway
      - ../sysadmin/db:/sql/sysadmin
      - ./init-db.sh:/init-db.sh #将主机的数据卷或者文件挂载到容器里
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #添加环境变量。您可以使用数组或字典、任何布尔值，布尔值需要用引号引起来，以确保 YML 解析器不会将其转换为 True 或 False。

networks:
  sc-net:
    external: false #配置容器连接的网络，引用顶级networks下的条目