version: '3'
services:
  konga:
    image: pantsel/konga #指定容器运行的镜像
    container_name: sc-konga #指定自定义容器名称，而不是生成的默认名称
    depends_on:
      - kong #设置依赖关系
    networks:
      - sc-net #配置容器连接的网络，引用顶级networks下的条目
    env_file: .env #从文件添加环境变量，可以是单个值或列表的多个值
    ports:
      - 1337:1337/tcp #本机映射的端口：容器端口

  kong:
    image: kong:latest #指定容器运行的镜像
    container_name: sc-kong #指定自定义容器名称，而不是生成的默认名称
    env_file: .env #从文件添加环境变量，可以是单个值或列表的多个值
    volumes:
      - ../data/kong:/usr/local/kong #将主机的数据卷或者文件挂载到容器里
    networks:
      - sc-net #配置容器连接的网络，引用顶级networks下的条目
    ports:
      - 18000:8000/tcp
      - 18443:8443/tcp
      - 18001:8001/tcp
      - 8444:8444/tcp #本机映射的端口：容器端口
    depends_on:
      - postgres #设置依赖关系
