version: '3'
services:
  nacos:
    image: nacos/nacos-server:1.2.1 #指定容器运行的镜像
    container_name: sc-nacos-standalone #指定自定义容器名称，而不是生成的默认名称
    networks:
      - sc-net #配置容器连接的网络，引用顶级networks下的条目
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone #添加环境变量。您可以使用数组或字典、任何布尔值，布尔值需要用引号引起来，以确保 YML 解析器不会将其转换为 True 或 False。
    volumes:
      - ../data/nacos-server/logs/:/home/nacos/logs #将主机的数据卷或者文件挂载到容器里
    ports:
      - "8848:8848" #本机映射的端口：容器端口

  prometheus:
    container_name: sc-prometheus #指定自定义容器名称，而不是生成的默认名称
    image: prom/prometheus:latest #指定容器运行的镜像
    networks:
      - sc-net #配置容器连接的网络，引用顶级networks下的条目
    volumes:
      - ./nacos/prometheus.yaml:/etc/prometheus/prometheus.yml #将主机的数据卷或者文件挂载到容器里
    ports:
      - "9090:9090" #本机映射的端口：容器端口
    depends_on:
      - nacos #设置依赖关系
    restart: on-failure     #在容器非正常退出时（退出状态非0），才会重启容器。