version: '3'
services:
  #消息中心
  bus-server:
    image: cike/bus-server:latest #指定容器运行的镜像
    container_name: sc-bus #指定自定义容器名称，而不是生成的默认名称
    restart: always #容器总是重新启动
    networks:
      - sc-net #配置容器连接的网络，引用顶级networks下的条目
    ports:
      - 8071:8071 #本机映射的端口：容器端口
    env_file: .env #从文件添加环境变量，可以是单个值或列表的多个值
    environment:
      TZ: Asia/Shanghai #添加环境变量。您可以使用数组或字典、任何布尔值，布尔值需要用引号引起来，以确保 YML 解析器不会将其转换为 True 或 False。